# info
info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@
    encoding: @project.build.sourceEncoding@
    java:
      version: @java.version@

# idp
idp:
  base-url: http://172.20.20.87:9080
  base-url-https: https://vneid.teca.vn
  issuer-uri: ${idp.base-url}/auth/realms/citizen
  jwk-set-uri: ${idp.base-url}/auth/realms/citizen/protocol/openid-connect/certs

# spring
spring:
  application:
    name: sh-migrate
  sleuth:
    sampler:
      probability: 1
  zipkin:
    enabled: false

  # cloud
  cloud:
    config:
      enabled: false
    bus:
      destination: service-cloud-bus
      enabled: false
  # messages
  messages:
    basename: messages
    encoding: UTF-8
  # jackson
  jackson:
    time-zone: Asia/Ho_Chi_Minh
    date-format: dd/MM/yyyy HH:mm:ss
  # datasource
  datasource:
    url: jdbc:oracle:thin:@//172.20.20.67:1521/dbdev
    username: SH_SYSTEM
    password: SH_SYSTEM
    driver-class-name: oracle.jdbc.driver.OracleDriver
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 20
  # Http Client
  http-client:
    close-idle-connection-wait-time: 30000
    connect-timeout: 30000
    keep-alive-time: 20000
    max-total-connection: 100
    request-timeout: 30000
    socket-timeout: 60000
    thread-pool-size: 50

# eureka
eureka:
  client:
    service-url:
      defaultZone: http://digitization:digitization2023@10.100.131.243:8001/eureka/
    register-with-eureka: false
    enabled: false
  instance:
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}
    prefer-ip-address: true

# management
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
  info:
    env:
      enabled: true

# services
rest:
  connect-timeout: 30s
  read-timeout: 30s
  services:
    idp: http://sh-idp
