# info
info:
  app:
    name: sh-migrate
    description: Digitization Migrate
    version: 0.0.1-SNAPSHOT
    encoding: UTF-8
    java:
      version: 1.8.0_202

# spring
spring:
  application:
    name: sh-migrate
  sleuth:
    sampler:
      probability: 1
  zipkin:
    enabled: false

  # messages
  messages:
    basename: messages
    encoding: UTF-8
  # jackson
  jackson:
    time-zone: Asia/Ho_Chi_Minh
    date-format: dd/MM/yyyy HH:mm:ss

  # Http Client
  http-client:
    close-idle-connection-wait-time: 30000
    connect-timeout: 30000
    keep-alive-time: 20000
    max-total-connection: 100
    request-timeout: 30000
    socket-timeout: 60000
    thread-pool-size: 50

# management
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
  info:
    env:
      enabled: true
